Update tradelog

diff --git a/tradelog b/tradelog
--- a/tradelog
+++ b/tradelog
@@ -5,6 +5,13 @@
 # @login : xkachy00
 # @date : 2021-04-04
 # @usage : type --help or -h
+#!/bin/sh
+# =============================================================
+# IOS - project 1
+# @author : Tadeáš Kachyňa
+# @login  : xkachy00
+# @date   : 2021-04-06
+# @usage  : type "--help" or "-h"
 # =============================================================
 
 export POSIXLY_CORRECT=yes
@@ -13,9 +20,9 @@ export LC_NUMERIC=en_US.UTF-8
 # This function might help you, if you get lost
 help()
 {
-    echo "Usage: tradelog [-h|--help] [FILTER] [COMAND] [LOG [LOG2 [...]]"
-
     echo "============================================================="
+
+    echo "Usage: tradelog [-h|--help] [FILTER] [COMAND] [LOG [LOG2 [...]]"
 
     echo "One of the commands can be:"
     echo "  list-tick – listing of occurring stock exchange symbols, so-called tickers"
@@ -26,7 +33,7 @@ help()
     echo "  graph-pos – statement of the graph of values of held positions according to the ticker"
 
     echo "The FILTER can be a combination of the following:"
-    echo "  -a DATETIME – after: only records after this date are considered (without this date). DATETIME is in the format YYYY-MM-DD HH: MM: SS"
+    echo "  -a DATETIME – after: only records after this date are considered (without this date). DATETIME is in the format YYYY-MM-DD HH:MM:SS"
     echo "  -b DATETIME – before: only records BEFORE this date (without this date) are considered"
     echo "  -t TICKER – only entries corresponding to a given ticker are considered. With multiple occurrences of the switch, the set of all listed ticker is taken"
     echo "  -w WIDTH – in the list of graphs, sets their width, ie the length of the longest line to WIDTH. Thus, WIDTH must be a positive integer. Multiple occurrences of the switch is a faulty start"
@@ -37,14 +44,14 @@ help()
 ########## Loading Logs ########## 
 
 NUMBER_OF_LOGS=0        # defines the final number by how much to shift, default is set to zero
-WIDTH=0                 # defines the flag width, default is set to zero
+WIDTH=0                 # defines the flag width, by default it is set to zero
 
 # loops through arguments
 for var in "$@" ; do  
     
     # condition checking whether it is a file or not
-    if [ -f "$var" ]; then
-
+    if [ -e "$var" ] ; then
+     
         case "$var" in
 
         # LOG files
@@ -57,24 +64,23 @@ $LOADING_LOG"
             LOG=$(echo "$LOG" | awk 'NF')
             ;;
 
-        # LOG.GZ files
-        *.log.gz)
+        # ,GZ files
+        *.gz)
             NUMBER_OF_LOGS=$((NUMBER_OF_LOGS+1))
             LOADING_LOG=$(gunzip -d -c "$var")
 
             LOG="${LOG}$LOADING_LOG"
             ;;
 
-        # Wrong format 
+        # Invalid format 
         *)   
-            echo "ERROR > Wrong format. Only *.log and *.log.gz are supported!"
+            echo "ERROR > Invalid format. Only *.log and *.gz are supported!" >&2
             exit 1
             ;;
             
-        esac
+        esac   
     fi
-done
-
+done 
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then help ; exit 0; fi  # prints only help
 if [ -z "$LOG" ]; then LOG=$(cat - | awk 'NF') ; fi                 # reads from standart input, when it does not recieve any file
@@ -88,10 +94,10 @@ while getopts ":t:a:b:w:h:help" opt; do
 
     # -t TICKER – only entries corresponding to a given ticker are considered. With multiple occurrences of the switch, the set of all listed ticker is taken
     t)  
-        # condition checking whether the name of ticket is correct or not
+        # condition checking whether the name of a ticket is correct or not
         ERROR=$(echo "$TICKERS" | grep -w "$OPTARG")
         if [ -z "$ERROR" ] ; then  
-            echo "ERROR > Wrong ticker!"
+            echo "ERROR > Invalid ticker!"
             exit 1 
         fi
         
@@ -101,13 +107,13 @@ $OPTARG"
 
     # -a DATETIME – after: only records after this date are considered (without this date). DATETIME is in the format YYYY-MM-DD HH: MM: SS
     a)  
-        # checking date format YYYY-MM-DD HH:MM:SS (1 = corect, 0 = wrong).
+        # checking date format YYYY-MM-DD HH:MM:SS (1 = valid, 0 = invalid).
         DATE_FORMAT=$(echo "$OPTARG" | awk  -F '[: -]' '{ print (match($1, /^[0-9][0-9][0-9][0-9]$/) && $2 <= 12 && $3 <= 31 && $4 <= 23 && $5 <= 60 && $6 <= 60) ? 0 : 1 }')
 
         # condition - prints error, when the date format is not correct
         if [ "$DATE_FORMAT" = 1 ]
         then
-            echo "Wrong date format! Correct format is YYYY-MM-DD HH:MM:SS."
+            echo "ERROR > Invalid date format! Correct format is YYYY-MM-DD HH:MM:SS." >&2
             exit 1
         fi
 
@@ -117,13 +123,13 @@ $OPTARG"
 
     # -b DATETIME – before: only records BEFORE this date (without this date) are considered
     b)  
-        # checking date format YYYY-MM-DD HH:MM:SS (1 = corect, 0 = wrong).
+        # checking date format YYYY-MM-DD HH:MM:SS (1 = valid, 0 = invalid).
         DATE_FORMAT=$(echo "$OPTARG" | awk  -F '[: -]' '{ print (match($1, /^[0-9][0-9][0-9][0-9]$/) && $2 <= 12 && $3 <= 31 && $4 <= 23 && $5 <= 60 && $6 <= 60) ? 0 : 1 }')
 
          # condition - prints error, when the date format is not correct
         if [ "$DATE_FORMAT" = 1 ]
         then
-            echo "Wrong date format! Correct format is YYYY-MM-DD HH:MM:SS."
+            echo "ERROR > Invalid date format! Correct format is YYYY-MM-DD HH:MM:SS."
             exit 1
         fi
         
@@ -137,12 +143,12 @@ $OPTARG"
         WIDTH_COUNTER=$((WIDTH_COUNTER+1))
 
         if [ "$WIDTH_COUNTER" -ge 2 ] ; then
-            echo "ERROR > Flag -w can be entered only once!"
+            echo "ERROR > Flag -w can be entered only once!" >&2
             exit 1
         fi
 
-        if [ "$WIDTH" -le 0 ] ; then
-            echo "ERROR > Flag -w must be an unsigned integer!"
+        if [ "$WIDTH" -lt 0 ] ; then
+            echo "ERROR > Flag -w must be an unsigned integer!" >&2
             exit 1
         fi
         ;;
@@ -154,29 +160,27 @@ $OPTARG"
         ;;
 
     :)
-        # if -k flag, no value, OPTARG contains "k"; handle here
         echo "$OPTARG"
         ;;
 
     *)  
+        echo "ERROR > Invalid flag!" >&2
+        exit 1
         ;;
     esac
 done
 shift $((OPTIND-1))
 
-##########  Merging logs $ tickers based on flags ########## 
+##########  Merging logs $ tickers based on entered flags ########## 
 
 # Logs
-if [ "$after" = 1 ]
-then
+if [ "$after" = 1 ] ; then
     MERGED=$(echo "$LOG_AFTER" | sort )
     LOG="$MERGED"
-elif [ "$before" = 1 ]
-then
+elif [ "$before" = 1 ] ;then
     MERGED=$(echo "$LOG_BEFORE" | sort )
     LOG="$MERGED"
-elif [ "$before" = 1 ] && [ "$after" = 1 ]
-then
+elif [ "$before" = 1 ] && [ "$after" = 1 ] ;then
     MERGED=$(echo "$LOG_BEFORE $LOG_BEFORE" | sort )
     LOG="$MERGED"
 fi
@@ -184,8 +188,7 @@ fi
 # Tickers
 TICKERS="$(echo "$LOG" | awk -F ';' '{print $2}' | sort -u)"
 
-if [ -z "$SELECTED_TICKERS" ]
-then
+if [ -z "$SELECTED_TICKERS" ] ;then
     TICKERS=$TICKERS 
 else
     TICKERS=$(echo "$SELECTED_TICKERS"  | sort | awk 'NF' )
@@ -194,12 +197,24 @@ else
 $(echo "$LOG" | grep -w "$a")"
     done
     LOG=$(echo "$LOGG" | sort -k1 )
-  
 fi
 
-# ========== Commands ========== 
+# Checking arguments
+for var in "$@" ; do
+    if    [ "$var" = "list-tick" ] ; then continue
+    elif  [ "$var" = "profit" ]    ; then continue
+    elif  [ "$var" = "pos" ]       ; then continue
+    elif  [ "$var" = "last-price" ]; then continue
+    elif  [ "$var" = "hist-ord" ]  ; then continue
+    elif  [ "$var" = "graph-pos" ] ; then continue
+    elif  [  -f "$var" ]           ; then continue
+    else echo "ERROR > Invalid argument" >&2  ; exit 1
+    fi
+done
 
-# the main loop - goes until the number of arguments is greater than zero
+########## Commands ########## 
+
+# the main loop
 while [ "$#" -gt 0 ] ; do
     case "$1" in
 
@@ -286,7 +301,8 @@ $a:$POS_RESULT1"
             NUM_OF_OCC=$(echo "$LOG"|  awk -F ';' -v lvar="$a" '$2==lvar {print $0}' | awk 'END{print NR}')
             
             RESULT=$(echo "$NUM_OF_OCC" | awk  -v var="$NUM_OF_OCC" -v max="$HIGHEST" -v wid="$WIDTH" '  { if(wid != 0) {sum=(wid/max)*var} else {sum=var/1} } END{printf "%0.f", int(sum)}')
-    
+
+            # tranforms numbers into equivalent representation in ASCII signs
             PRINTING_GRAPH=$(echo "$RESULT" | awk -v var="$RESULT" '{
             if (var > 0)
             { 
@@ -303,20 +319,21 @@ $a:$POS_RESULT1"
         done
         shift
         ;;
-    # graph-pos – výpis grafu hodnot držených pozic dle tickeru
+
+    # graph-pos – statement of the graph of values of held positions according to the ticker
     graph-pos)
          for a in $TICKERS
         do  
-            # getting bought stocks for each ticket and add it to a var "sum"
+            # gets bought stocks for each ticket and add it to a var "sum"
             POS_BUY=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2==lvar && $3 ~ /buy/ {sum += $6} END {printf "%.0f", sum}')
 
-            # getting sold stocks for each ticket and add it to a var "sum"
+            # gets sold stocks for each ticket and add it to a var "sum"
             POS_SELL=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2==lvar && $3 ~ /sell/ {sum += $6} END {printf "%.0f", sum}')
 
             # "sold" - "bought"
             POS_RESULT="$(echo "$POS_BUY - $POS_SELL" | bc)"
 
-            # getting the last transaction
+            # gets the last transaction
             POS_LAST_TRANS="$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2==lvar {print $0}' | tail -n1 | awk -F ';' '{print $4}')"
 
             POS_RESULT1=$(echo "$POS_RESULT*$POS_LAST_TRANS"| bc)
@@ -324,16 +341,17 @@ $a:$POS_RESULT1"
 $POS_RESULT1" 
         done 
 
-            POSR=$(echo "$POS_RESULT3"| awk 'NF')
-            MAX_VAL=$(echo "$POSR" | tr ' ' '\n' | tr '-' ' ' | sort -nr | head -1)
+            # gets the biggest value ( removes minus sign - sorts by number - takes the fist number)
+            MAX_VAL=$(echo "$POS_RESULT3" |   tr ' ' '\n' | tr '-' ' ' | sort -nr | head -1) 
 
             for a in $POS_RESULT3 ; do
         
+            # gets each value real graph represantation if flag -w is entered
             TEST1=$(echo "$a" | awk  -v var="$a" -v max="$MAX_VAL" -v wid="$WIDTH" '  { if(wid != 0) {sum=(wid/max)*var} else {sum=var/1000} } END{printf "%0.f", int(sum)}')
           
+            # tranforms numbers into equivalent representation in ASCII signs
             TEST=$(echo "$TEST1" | awk -v var="$TEST1" '{
-            if (var > 0)
-            {  
+            if (var > 0) { 
                s = sprintf("%*s", var, "")
                gsub(" ", "#", s)
                print s
@@ -345,21 +363,18 @@ $POS_RESULT1"
                 s=1
                 print s
             }}')
-        
-            
-            END="$END
+           
+            PRE_RESULT="$PRE_RESULT
 $TEST"
             done
             
-            ENND=$(echo "$END"| awk '{printf "%s ", $1} ENDFILE {print ""}')
+            RESULT=$(echo "$PRE_RESULT"| awk '{printf "%s ", $1} ENDFILE {print ""}')
             TICKERSS=$(echo "$TICKERS"| awk '{printf "%s ", $1} ENDFILE {print ""}')
-  
-            echo "$ENND" | awk -F " "  -v var="$TICKERSS" -v vvar="$ENND" 'BEGIN { split(var,a," ") split(vvar,b," ") } END {
-           
-            for(i=1;i in a;i++) 
-            {   
-                if (b[i] != 1)
-            {
+    
+            # printing the result
+            echo "$RESULT" | awk -F " "  -v var_a="$TICKERSS" -v var_b="$RESULT" 'BEGIN { split(var_a,a," ") split(var_b,b," ") } END {
+            for(i=1;i in a;i++) {   
+                if (b[i] != 1) {
                printf "%-10s: %s\n", a[i],  b[i]
             } else if (b[i] == "1") {    
                printf "%-10s:\n", a[i]}
@@ -369,23 +384,19 @@ $TEST"
         shift 
         ;;
     
+    # this might help you
     --help)
         help
         exit 0
 
         ;;     
     *)  
-       
-        for a in $TICKERS ; do
-        VARa=$(echo "$LOG" | grep -w "$a")
-        VARb="$VARb
-$VARa"
-        done
-
-        echo "$VARb" | awk 'NF' | sort -k1
-        
+        # if no command(s) is/are entered
+        echo "$LOG" | awk 'NF'
         ;;
+
     esac
 
 shift "$NUMBER_OF_LOGS"
 done
+########## END OF THE SCRIPT ########## 
