Update tradelog

diff --git a/tradelog b/tradelog
--- a/tradelog
+++ b/tradelog
@@ -1,9 +1,11 @@
-#! /bin/sh
-# IOS - project 1
-# author : Tadeáš Kachyňa
-# login : xkachy00
-# date : 2021-04-04
-# usage : type --help or -h
+#! /bin/dash
+# =============================================================
+# @IOS - project 1
+# @author : Tadeáš Kachyňa
+# @login : xkachy00
+# @date : 2021-04-04
+# @usage : type --help or -h
+# =============================================================
 
 export POSIXLY_CORRECT=yes
 export LC_NUMERIC=en_US.UTF-8
@@ -12,6 +14,8 @@ export LC_NUMERIC=en_US.UTF-8
 help()
 {
     echo "Usage: tradelog [-h|--help] [FILTR] [PŘÍKAZ] [LOG [LOG2 [...]]"
+
+    echo "============================================================="
 
     echo "One of the commands can be:"
     echo "  list-tick – listing of occurring stock exchange symbols, so-called tickers"
@@ -26,103 +30,152 @@ help()
     echo "  -b DATETIME – before: only records BEFORE this date (without this date) are considered"
     echo "  -t TICKER – only entries corresponding to a given ticker are considered. With multiple occurrences of the switch, the set of all listed ticker is taken"
     echo "  -w WIDTH – in the list of graphs, sets their width, ie the length of the longest line to WIDTH. Thus, WIDTH must be a positive integer. Multiple occurrences of the switch is a faulty start"
+
+    echo "============================================================="
 }
 
-# loading file(s)
-for var in "$@"
-do  
+# ========== Loading Logs ==========
+
+# loop through arguments
+for var in "$@" ; do  
     
+    # condition checking whether it is a file or not
     if [ -f "$var" ]; then
-    i=$((i+1))
-    AB=$(cat "$var")
-    LOG="${LOG} $AB"
+
+        case "$var" in
+
+        # LOG files
+        *.log ) 
+            i=$((i+1))
+            AB=$(cat "$var")
+            LOG="${LOG} $AB"
+            ;;
+
+        # LOG.GZ files
+        *.log.gz)
+            i=$((i+1))
+            AB=$(gzcat "$var")
+            LOG="${LOG} $AB"
+            ;;
+
+        # Wrong format 
+        *)  
+            echo "ERROR > Wrong format. Only *.log and *.log.gz are supported!"
+            exit 1
+            ;;
+        esac     
     fi
 done
 
-# flags
-while getopts ":t:a:b:w:" opt; do
+
+# ========== Parsing Flags  ========== 
+
+while getopts ":t:a:b:w:h:help" opt; do
     case ${opt} in
 
     # -t TICKER – only entries corresponding to a given ticker are considered. With multiple occurrences of the switch, the set of all listed ticker is taken
     t)  
-        IFS=" "
-        TICKERSS="$TICKERSS $OPTARG"
-      
+        SELECTED_TICKERS="$SELECTED_TICKERS 
+$OPTARG"
         ;;
 
     # -a DATETIME – after: only records after this date are considered (without this date). DATETIME is in the format YYYY-MM-DD HH: MM: SS
     a)  
-        A=$(echo "$OPTARG"  | awk  -F '[:- ]' '{ print ($3 <= 31 && $2 <= 31 && $4 <= 31 && $5 <= 60 && $6 <= 60 && match($1, /^[0-9][0-9][0-9][0-9]$/)) ? "" : "1"}')
-        if [ "$A" = 1 ]
+
+        # checking date format YYYY-MM-DD HH:MM:SS.
+        DATE_FORMAT=$(echo "$OPTARG" | awk  -F '[: -]' '{ print (match($1, /^[0-9][0-9][0-9][0-9]$/) && $2 <= 12 && $3 <= 31 && $4 <= 23 && $5 <= 60 && $6 <= 60) ? 0 : 1 }')
+
+        # condition - prints error, when the date format is not correct
+        if [ "$DATE_FORMAT" = 1 ]
         then
-            echo "Wrong date format!"
+            echo "Wrong date format! Correct format is YYYY-MM-DD HH:MM:SS."
             exit 1
         fi
 
-       
-        
-       
-        LOGG=$(echo "$LOG" | awk '$0>from&&$0<to' from="$OPTARG" to="9999-99-99 23:59:59" | awk 'NF')
- 
+        after=1
+        LOG_AFTER=$(echo "$LOG" | awk '$0>from&&$0<to' from="$OPTARG" to="9999-99-99 23:59:59")
         ;;
 
     # -b DATETIME – before: only records BEFORE this date (without this date) are considered
-
     b)  
-        A=$(echo "$OPTARG"  | awk  -F '[:- ]' '{ print ($3 <= 31 && $2 <= 31 && $4 <= 31 && $5 <= 60 && $6 <= 60 && match($1, /^[0-9][0-9][0-9][0-9]$/)) ? "" : "1"}')
-        if [ "$A" = 1 ]
+        # checking date format YYYY-MM-DD HH:MM:SS.
+        DATE_FORMAT=$(echo "$OPTARG" | awk  -F '[: -]' '{ print (match($1, /^[0-9][0-9][0-9][0-9]$/) && $2 <= 12 && $3 <= 31 && $4 <= 23 && $5 <= 60 && $6 <= 60) ? 0 : 1 }')
+
+         # condition - prints error, when the date format is not correct
+        if [ "$DATE_FORMAT" = 1 ]
         then
-            echo "Wrong date format!"
+            echo "Wrong date format! Correct format is YYYY-MM-DD HH:MM:SS."
             exit 1
         fi
-
         
-  
-        LOGGA=$(echo "$LOG" | awk '$0>from&&$0<to' from="0000-00-00 00:00:00" to="$OPTARG" | awk 'NF')
-       
+        before=1
+        LOG_BEFORE=$(echo "$LOG" | awk '$0>from&&$0<to' from="0000-00-00 00:00:00" to="$OPTARG")
         ;;
 
     # -w WIDTH – in the list of graphs, sets their width, ie the length of the longest line to WIDTH. Thus, WIDTH must be a positive integer. Multiple occurrences of the switch is a faulty start
-    w)
-        WItdH="$OPTARG"
-       # i = int(width / maxCount * count)
-      
+    w)  
+        WIDTH="$OPTARG"
+
+        w=$((w+1))
+
+        if [ "$w" -ge 2 ] ; then
+            echo "ERROR > Flag -w can be entered only once!"
+            exit 1
+        fi
+
+        if [ "$WIDTH" -le 0 ] ; then
+            echo "ERROR > Flag -w must be an unsigned integer!"
+            exit 1
+        fi
+
         ;;
+    h)
+        help
+        exit 0
+        ;;
+
     :)
         # if -k flag, no value, OPTARG contains "k"; handle here
         echo "$OPTARG"
-   
         ;;
-    *)  
-        echo "Hello WOrld"
-        # sorted tickers 
 
+    *)  
+        echo "Wrong flag."
+        exit 1
         ;;
     esac
-
- 
 done
 shift $((OPTIND -1))
 
 
+# ========== Merging logs $ tickers based on flags ========== 
 
-
-if [ "$LOGG" ] && [ "$LOGGA" ]
+# Logs
+if [ "$after" = 1 ]
 then
-    UNIQUE=$(echo "$LOGG $LOGGA" | tr '' '\n' | sort | uniq -d)
-    LOG="$UNIQUE"
+    MERGED=$(echo "$LOG_AFTER" | sort )
+    LOG="$MERGED"
+elif [ "$before" = 1 ]
+then
+    MERGED=$(echo "$LOG_BEFORE" | sort )
+    LOG="$MERGED"
+elif [ "$before" = 1 ] && [ "$after" = 1 ]
+then
+    MERGED=$(echo "$LOG_BEFORE $LOG_BEFORE" | sort )
+    LOG="$MERGED"
 fi
 
+# Tickers
 TICKERS="$(echo "$LOG" | awk -F ';' '{print $2}' | sort -u)"
 
-
-if [ -z "$TICKERSS" ]
+if [ -z "$SELECTED_TICKERS" ]
 then
     TICKERS=$TICKERS 
 else
-    TICKERS=$(echo "$TICKERSS"  | xargs -n1 | sort | xargs)
+    TICKERS=$(echo "$SELECTED_TICKERS"  | sort |awk 'NF' )
 fi
 
+# ========== Commands ========== 
 
 # the main loop - goes until the number of arguments is greater than zero
 while [ "$#" -gt 0 ] ; do
@@ -156,7 +209,6 @@ while [ "$#" -gt 0 ] ; do
     
     # LAST-PRICE – listing of the last known price for each ticke
     last-price)
-    
 
         # search for the largest number in column no. 4
         for a in $TICKERS ; do LOGGA=${LOGGA}"\n"$(echo "$LOG" | awk -F ';' -v var="$a"  '$2 == var {print $0}') ; done
@@ -165,30 +217,32 @@ while [ "$#" -gt 0 ] ; do
     
         for a in $TICKERS ; do  
             # get all "$a" transactions => print the last one => align to the right by the longest number
-            echo "$LOG" | awk -F ';' -v var="$a"  '$2 == var {print $0}' |  awk -F ';' -v var="$a" -v len="$LENGTH" '$2 ~ var{a=$0} END{ printf "%-10s : %*s\n", var, len, $4}'
+            echo "$LOG" | awk -F ';' -v var="$a"  '$2 == var {print $0}' |  awk -F ';' -v var="$a" -v len="$LENGTH" '$2 ~ var{a=$0} END{ printf "%-10s: %*s\n", var, len, $4}'
      
         done
         shift
         ;;
+
     #POS – list of values of currently held positions sorted in descending order by value
     pos)
-       
+
         for a in $TICKERS
         do  
+           
             # getting bought stocks for each ticket and add it to a var "sum"
             POS_BUY=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2 ~ lvar && $3 ~ /buy/ {sum += $6} END {print sum}')
+            if [ -z "$POS_BUY" ] ; then  POS_SELL=0 ; fi
 
             # getting sold stocks for each ticket and add it to a var "sum"
-            POS_SELL=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2 ~ lvar && $3 ~ /sell/ {sum += $6} END {print sum}')
+            POS_SELL=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2 ~ lvar && $3 ~ /sell/ {sum += $6} if (length(sum) == 0){sum = 0} END {print sum}')
+            if [ -z "$POS_SELL" ] ; then  POS_SELL=0 ; fi
 
             # "sold" - "bought"
             POS_RESULT="$( echo "$POS_BUY - $POS_SELL" | bc)"
 
-            
-        
             # getting the last transaction
             POS_LAST_TRANS="$(echo "$LOG" | grep "$a" | tail -n1 | awk -F ';' '{print $4}')"
-
+           
             #echo "$VAR2"
             POS_RESULT1=$(echo  "$POS_RESULT*$POS_LAST_TRANS"| bc)
             POS_RESULT3="$POS_RESULT3
@@ -199,10 +253,7 @@ $a:$POS_RESULT1"
         LENGTH=$(echo "$POS_RESULT3" | awk -F ':' '{for (i=1;i<=NF;i++) if (length($2)>max) max=length($2)} END{print max}')
         
         echo "$POS_RESULT3" |  awk 'NF' | sort -t ':' -k2 -n -r |  awk -F ':' -v var="$LENGTH"  '{printf ("%-10s: %*s\n", $1, var, $2)}'
-     
-        
-      
-
+   
         shift
         ;;  
 
@@ -221,20 +272,20 @@ $a:$POS_RESULT1"
             print s p
             }')
 
-            printf "%-11s : %s\n" "$a" "$VARc"
+            printf "%-10s: %s\n" "$a" "$VARc"
 
         done
         shift
         ;;
     # graph-pos – výpis grafu hodnot držených pozic dle tickeru
     graph-pos)
-        for a in $TICKERS
+         for a in $TICKERS
         do  
             # getting bought stocks for each ticket and add it to a var "sum"
-            POS_BUY=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2 ~ lvar && $3 ~ /buy/ {sum += $6} END {print sum}')
+            POS_BUY=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2 ~ lvar && $3 ~ /buy/ {sum += $6} END {printf "%.0f", sum}')
 
             # getting sold stocks for each ticket and add it to a var "sum"
-            POS_SELL=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2 ~ lvar && $3 ~ /sell/ {sum += $6} END {print sum}')
+            POS_SELL=$(echo "$LOG" | awk -F ';' -v lvar="$a" '$2 ~ lvar && $3 ~ /sell/ {sum += $6} END {printf "%.0f", sum}')
 
             # "sold" - "bought"
             POS_RESULT="$( echo "$POS_BUY - $POS_SELL" | bc)"
@@ -243,19 +294,29 @@ $a:$POS_RESULT1"
         
             # getting the last transaction
             POS_LAST_TRANS="$(echo "$LOG" | grep "$a" | tail -n1 | awk -F ';' '{print $4}')"
-
+            echo "hlaska" 1>&a
             #echo "$VAR2"
-            POS_RESULT2=$(echo "$POS_RESULT*$POS_LAST_TRANS"| bc)
-            POS_RESULT3=$(echo "$POS_RESULT2/100000"| bc),
-            
+            POS_RESULT1=$(echo  "$POS_RESULT*$POS_LAST_TRANS"| bc)
+            POS_RESULT3="$POS_RESULT3
+$POS_RESULT1" 
+        done 
 
-            TEST=$(echo "$POS_RESULT3" | awk -v var="$POS_RESULT3" -v w="$WITDH" '{
+            POSR=$(echo "$POS_RESULT3"| awk 'NF')
+            MAX_VAL=$(echo "$POSR" | tr ' ' '\n' | sort -n | head -1)
+
+            IFS="
+" 
+            for a in $POS_RESULT3 ; do
+        
+            TEST1=$(echo "$a" | awk  -v var="$a" -v max="$MAX_VAL" -v wid="$WIDTH" '  {sum=(wid/max)*var} END{print sum}')
+                
+            TEST=$(echo "$TEST1" | awk -v var="$TEST1" '{
             if (var >= 0)
             {
                s = sprintf("%*s", $1, " ")
                gsub(/ /, "#", s)
                print s p
-            } else {
+            } else {    
                s = sprintf("%*s", $1, " ")
                gsub(/ /, "!", s)
                print s p
@@ -263,29 +324,25 @@ $a:$POS_RESULT1"
             
             }')
 
-            printf  "%-10s: %s\n" "$a" "$TEST"   
-
+            END="$END 
+$TEST"
+            done
         
-        done  
-        shift
+            AVE=$(printf '%s\n' "$TICKERS" "$END" | pr -2 -t  )
+
+            echo "$AVE" | awk -F " " '{printf "%-10s : %s\n", $1,  $2}'
+                    
+        shift 
         ;;
     
-    # This might help you, if you get lost
-  
-    -h)
-        help
-        exit 0
-        ;;
+    --help)
 
-     # This also might help you, if you get lost
-    -help)
+
         help
         exit 0
-        ;;
-               
+
+        ;;     
     *)  
-
-        
         for a in $TICKERS
         do
         TESTB=$(echo "$LOG" | grep -w "$a")
@@ -294,9 +351,12 @@ $TESTB"
         done
         
         echo "$TESTA" | awk 'NF' | sort -k1
-     
         ;;
         
     esac
+
+
 shift "$i"
 done
+
+# ========== COMMANDS ========== END
